### ISSUE TITLE
IsExternal error message

### ISSUE THREAD

**Issue by Maddog164** [learn-co-curriculum/js-advanced-functions-context-lab#16]
when running learn on this lab, I continued to get a isExternal error message learn test

> javascript-lab@1.0.0 test
> mocha --timeout 30000 -R mocha-multi --reporter-options spec=-,json=.results.json

TypeError: Cannot set property 'isExternal' of undefined
    at extend (/home/denise/development/flatiron/labs/js-advanced-functions-context-lab-onl01-seng-pt-070620/node_modules/file-system/vendor/util.js:34:19)
    at extend (/home/denise/development/flatiron/labs/js-advanced-functions-context-lab-onl01-seng-pt-070620/node_modules/file-system/vendor/util.js:32:7)
    at Object.<anonymous> (/home/denise/development/flatiron/labs/js-advanced-functions-context-lab-onl01-seng-pt-070620/node_modules/file-system/vendor/util.js:41:1)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/home/denise/development/flatiron/labs/js-advanced-functions-context-lab-onl01-seng-pt-070620/node_modules/file-system/index.js:6:12)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/home/denise/development/flatiron/labs/js-advanced-functions-context-lab-onl01-seng-pt-070620/test/helpers.js:4:12)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.exports.requireOrImport (/home/denise/development/flatiron/labs/js-advanced-functions-context-lab-onl01-seng-pt-070620/node_modules/mocha/lib/esm-utils.js:42:12)
    at Object.exports.loadFilesAsync (/home/denise/development/flatiron/labs/js-advanced-functions-context-lab-onl01-seng-pt-070620/node_modules/mocha/lib/esm-utils.js:55:34)
    at Mocha.loadFilesAsync (/home/denise/development/flatiron/labs/js-advanced-functions-context-lab-onl01-seng-pt-070620/node_modules/mocha/lib/mocha.js:431:19)
    at singleRun (/home/denise/development/flatiron/labs/js-advanced-functions-context-lab-onl01-seng-pt-070620/node_modules/mocha/lib/cli/run-helpers.js:125:15)
    at exports.runMocha (/home/denise/development/flatiron/labs/js-advanced-functions-context-lab-onl01-seng-pt-070620/node_modules/mocha/lib/cli/run-helpers.js:190:10)
    at Object.exports.handler (/home/denise/development/flatiron/labs/js-advanced-functions-context-lab-onl01-seng-pt-070620/node_modules/mocha/lib/cli/run.js:362:11)
    at /home/denise/development/flatiron/labs/js-advanced-functions-context-lab-onl01-seng-pt-070620/node_modules/yargs/build/index.cjs:443:71
npm ERR! code 1
npm ERR! path /home/denise/development/flatiron/labs/js-advanced-functions-context-lab-onl01-seng-pt-070620
npm ERR! command failed
npm ERR! command sh -c mocha --timeout 30000 -R mocha-multi --reporter-options spec=-,json=.results.json

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/denise/.npm/_logs/2021-03-07T15_57_16_511Z-debug.log
[10:57:16]  js-advanced-functions-context-lab-onl01-seng-pt-070620 (master)
// ♥  Traceback (most recent call last):
        11: from /home/denise/.rvm/gems/ruby-2.6.1/bin/ruby_executable_hooks:24:in `<main>'
        10: from /home/denise/.rvm/gems/ruby-2.6.1/bin/ruby_executable_hooks:24:in `eval'
         9: from /home/denise/.rvm/gems/ruby-2.6.1/bin/learn-test:23:in `<main>'
         8: from /home/denise/.rvm/gems/ruby-2.6.1/bin/learn-test:23:in `load'
         7: from /home/denise/.rvm/gems/ruby-2.6.1/gems/learn-test-3.3.1/bin/learn-test:73:in `<top (required)>'
         6: from /home/denise/.rvm/gems/ruby-2.6.1/gems/learn-test-3.3.1/lib/learn_test/runner.rb:21:in `run'
         5: from /home/denise/.rvm/gems/ruby-2.6.1/gems/learn-test-3.3.1/lib/learn_test/runner.rb:21:in `fork'
         4: from /home/denise/.rvm/gems/ruby-2.6.1/gems/learn-test-3.3.1/lib/learn_test/runner.rb:22:in `block in run'
         3: from /home/denise/.rvm/gems/ruby-2.6.1/gems/learn-test-3.3.1/lib/learn_test/runner.rb:49:in `report_and_clean'
         2: from /home/denise/.rvm/gems/ruby-2.6.1/gems/learn-test-3.3.1/lib/learn_test/reporter.rb:13:in `report'
         1: from /home/denise/.rvm/gems/ruby-2.6.1/gems/learn-test-3.3.1/lib/learn_test/reporter.rb:47:in `report'
/home/denise/.rvm/gems/ruby-2.6.1/gems/learn-test-3.3.1/lib/learn_test/strategies/mocha.rb:44:in `results': undefined method `[]' for nil:NilClass (NoMethodError)

Ultimately, I commented out the const fs (line 4), html (line 12), and modified line 23 to just refer to src in the test/helpers.js file to get around the error

**Comment by lizbur10** [comment]
Hi @Maddog164 ! Good work figuring this out! 

We've been seeing this error on labs where students run `npm audit fix` or `npm audit fix --force` as recommended in the terminal. We are working on a solution to the problem but, in the meantime, you should be able to ignore the deprecation warnings as long as the tests are running. If you don't run `npm audit fix`, you should stop getting this error.

Sorry about the inconvenience! 💙
